### ISSUE TITLE
[Bug] The Aleo SDK is not working

### ISSUE THREAD

**Issue by alexanderblv** [AleoHQ/aleo#890]
## 🐛 Bug Report
At the moment, the Aleo SDK is not working. It's not a bug, but the fact that it's just not connected to Testnet Beta. I think this needs to be fixed as soon as possible, because applications are much easier to deploy through Provable.Tools. This problem is pretty easy to solve, let's do it. 

https://www.provable.tools/account

cc: @howardwu @iamalwaysuncomfortable @raychu86 
-->

(Write your description here)

#### Code snippet to reproduce

```
# Add code here
```

#### Stack trace & error message

```
// Paste the output here
```

## Expected Behavior

(Write what you expected to happen here)

## Your Environment

- 
- 
-

**Comment by iamalwaysuncomfortable** [comment]
@alexanderblv we recently published a new SDK, has this been resolved on your end?

**Comment by alexanderblv** [comment]
> @alexanderblv we recently published a new SDK, has this been resolved on your end?

![image](https://github.com/user-attachments/assets/1931e849-ff47-4f64-9370-f3384b0c0aa4)
It seems not, I still can't deploy my program.

**Comment by iamalwaysuncomfortable** [comment]
@alexanderblv the CORS issue was fixed today, can you see if this fixes your issue?

**Comment by alexanderblv** [comment]
> @alexanderblv the CORS issue was fixed today, can you see if this fixes your issue?

It seems that the problem is still not solved, I get an error both when trying to deploy the program and when calculating the commission.
![image](https://github.com/user-attachments/assets/c01e80d2-2ee3-499c-9a7b-4c2f7d291b8d)

At the same time, I only get an endless loading animation.
![image](https://github.com/user-attachments/assets/26a4b7b2-41a4-4255-a140-811175524910)

**Comment by alexanderblv** [comment]
> > @alexanderblv the CORS issue was fixed today, can you see if this fixes your issue?
> 
> It seems that the problem is still not solved, I get an error both when trying to deploy the program and when calculating the commission. ![image](https://private-user-images.githubusercontent.com/137616408/354715755-c01e80d2-2ee3-499c-9a7b-4c2f7d291b8d.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjI2Nzg0MTQsIm5iZiI6MTcyMjY3ODExNCwicGF0aCI6Ii8xMzc2MTY0MDgvMzU0NzE1NzU1LWMwMWU4MGQyLTJlZTMtNDk5Yy05YTdiLTRjMmY3ZDI5MWI4ZC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwODAzJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDgwM1QwOTQxNTRaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1kNmY1ZDI2ZmZhNjM2MGM4MjIxM2FjY2I1NGFlODI0ZThhOWYwMTc5ZDJlOTZhOTkxYTBhZWI3NWQ4ODFhYThlJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.MTe9sKAhPS2EEsq5M-m85ZH1EsKddgGeuFTe-v3QZ2g)
> 
> At the same time, I only get an endless loading animation. ![image](https://private-user-images.githubusercontent.com/137616408/354716081-26a4b7b2-41a4-4255-a140-811175524910.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjI2Nzg0MTQsIm5iZiI6MTcyMjY3ODExNCwicGF0aCI6Ii8xMzc2MTY0MDgvMzU0NzE2MDgxLTI2YTRiN2IyLTQxYTQtNDI1NS1hMTQwLTgxMTE3NTUyNDkxMC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwODAzJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDgwM1QwOTQxNTRaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT05NGYyNzdkYTEzZWI2MGVlZDQxMzE4MjIzOGIwYzY3ZmM0OTZhNGNlM2ZkNjY1ZjdmY2RlNTUwZDdiYjBiMDkzJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.Nz8A71r7flPFuZpUQZmcIIOFLX_R8_DTd5GzEHdbxpQ)

@iamalwaysuncomfortable
